# Generated by Django 3.0.4 on 2020-03-13 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='项目名')),
                ('src_link', models.URLField(blank=True, null=True, verbose_name='SRC链接')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record', models.CharField(max_length=200, verbose_name='记录')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_modify_time', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
                ('type', models.CharField(blank=True, max_length=50, null=True, verbose_name='类型')),
                ('source', models.CharField(blank=True, max_length=50, null=True, verbose_name='来源')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.Project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '记录',
                'verbose_name_plural': '记录',
            },
        ),
    ]
