# Generated by Django 3.0.4 on 2020-03-08 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='类型'),
        ),
    ]
