# Generated by Django 3.0.4 on 2020-04-06 02:08

from django.db import migrations, models
import django.db.models.deletion
import entities.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='项目名')),
                ('src_link', models.URLField(blank=True, null=True, verbose_name='SRC链接')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='工具名')),
                ('link', models.URLField(blank=True, null=True, verbose_name='项目地址')),
                ('type', models.CharField(max_length=50, verbose_name='记录类型')),
                ('parse_class_name', models.CharField(max_length=50, verbose_name='输出解析类')),
                ('command', models.CharField(max_length=500, validators=[entities.validators.command_validator], verbose_name='调用命令')),
                ('input_type', models.CharField(choices=[('file', '文件'), ('parameter', '参数')], default='file', max_length=50, verbose_name='输入参数类型')),
                ('version', models.CharField(blank=True, max_length=50, null=True, verbose_name='版本')),
                ('comment', models.CharField(blank=True, max_length=100, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '工具表',
                'verbose_name_plural': '工具表',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='任务名')),
                ('input', models.TextField(verbose_name='输入')),
                ('input_file_type', models.CharField(choices=[('static_file', '静态'), ('dynamic_file', '动态')], default='static_file', max_length=50, verbose_name='输入文件类型')),
                ('dispatch', models.CharField(max_length=100, validators=[entities.validators.cron_validator], verbose_name='调度')),
                ('active', models.BooleanField(default=True, verbose_name='是否生效')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.Project', verbose_name='所属项目')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.Tool', verbose_name='工具')),
            ],
            options={
                'verbose_name': '任务表',
                'verbose_name_plural': '任务表',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record', models.CharField(max_length=200, verbose_name='记录')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_modify_time', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
                ('type', models.CharField(blank=True, max_length=50, null=True, verbose_name='类型')),
                ('source', models.CharField(blank=True, max_length=50, null=True, verbose_name='来源')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.Project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '记录',
                'verbose_name_plural': '记录',
            },
        ),
        migrations.CreateModel(
            name='BatchTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='批量任务名')),
                ('dispatch', models.CharField(max_length=100, validators=[entities.validators.cron_validator], verbose_name='调度')),
                ('active', models.BooleanField(default=True, verbose_name='是否生效')),
                ('task1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task1', to='entities.Task', verbose_name='任务1')),
                ('task10', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task10', to='entities.Task', verbose_name='任务10')),
                ('task2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task2', to='entities.Task', verbose_name='任务2')),
                ('task3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task3', to='entities.Task', verbose_name='任务3')),
                ('task4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task4', to='entities.Task', verbose_name='任务4')),
                ('task5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task5', to='entities.Task', verbose_name='任务5')),
                ('task6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task6', to='entities.Task', verbose_name='任务6')),
                ('task7', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task7', to='entities.Task', verbose_name='任务7')),
                ('task8', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task8', to='entities.Task', verbose_name='任务8')),
                ('task9', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task9', to='entities.Task', verbose_name='任务9')),
            ],
            options={
                'verbose_name': '批量任务表',
                'verbose_name_plural': '批量任务表',
            },
        ),
    ]
